### ISSUE TITLE
Games dont work

### ISSUE THREAD

**Issue by ItzJackOn** [thelowsunoverthemoon/Arcade.bat#1]
none of the games work.

**Comment by thelowsunoverthemoon** [comment]
Hmm they work fine for me. The games only work on Windows 10 or above on the CMD, NOT the windows terminal. Also try running as admin and follow the instructions for each. (Eg for some you have to save in utf-8 format, check the reddit posts on the descriptions)

**Comment by ItzJackOn** [comment]
I didnt find it via reddit

**Comment by thelowsunoverthemoon** [comment]
Try the steps I listed above. The requirements are also in the little description for each one in the repository.

**Comment by ItzJackOn** [comment]
I did.

**Comment by ItzJackOn** [comment]
it still doesnt work.

**Comment by thelowsunoverthemoon** [comment]
Give me some more details. What and where doesn't it work? Hard to say when you don't give me any details.
